// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function PlayMagnet(arg1) {
  return window['go']['main']['App']['PlayMagnet'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
