// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenLink(arg1:string):void;

export function PlayMagnet(arg1:string):void;

export function Search(arg1:string):Promise<Array<main.SearchResult>>;
